apiVersion: apps/v1
kind: Deployment
metadata:
    name: nginx
    namespace: production
spec:
    replicas: 2
    selector:
      matchLabels:
        app: nginx
    strategy:
        type: RollingUpdate
        rollingUpdate:
          maxSurge: 50%
          maxUnavailable: 50%
    template:
      metadata:
        labels:
          app: nginx
      spec:
        containers:
          - name: nginx
            image: docker.io/nginx:latest
            imagePullPolicy: "Always"
            ports:
              - containerPort: 80
            env:
              - name: TRACE_URL
                value: "http://trace.domain.com"
              - name: AUTH_URL
                value "http://auth.domain.com"
            resources:
              requests:
                cpu: '0'
                memory: '0'
              limits:
                cpu: '256'
                memory: 11400G
---
apiVersion: v1
kind: Service
metadata:
    name: nginx
    namespace: production
spec:
    ports:
      - targetPort: 80
        name: nginxhttp
        port: 8081
    selector:
      app: nginx

