apiVersion: apps/v1
kind: Deployment
metadata:
    name: nginx
    namespace: {{namespace}}
spec:
    replicas: 2
    selector:
      matchLabels:
        app: nginx
    strategy:
      type: RollingUpdate
      rollingUpdate:
        maxSurge: 50%
        maxUnavailable: 50%
    template:
      metadata:
        labels:
          app: nginx
      spec:
        nodeSelector:
          kubernetes.io/os: linux
        containers:
          - name: nginx
            image: nginx
            imagePullPolicy: "Always"
            readinessProbe:
              httpGet:
                path: /
                port: 80
              initialDelaySeconds: 5
              periodSeconds: 10
            ports:
              - containerPort: 80
            resources:
              requests:
                cpu: '0'
                memory: '0'
              limits:
                cpu: '256'
                memory: 11400G

---

apiVersion: v1
kind: Service
metadata:
  namespace: {{namespace}}
  name: ideabox-user-service
spec:
  selector:
    app: ideabox-user
  ports:
    - port: {{publishPort}}
      name: {{portName}}
      targetPort: 80