name: Generate release-artifacts

on:
  release:
    types: 
        - created

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Test
      run: make test
  generate:
    needs: test
    name: Generate cross-platform builds
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Generate build files
        uses: thatisuday/go-cross-build@v1
        with:
            platforms: 'linux/amd64'
            package: ''
            name: 'crab-cli'
            compress: 'false'
            dest: 'dist'
            
            
